#!/usr/bin/env bash
#print "Best school" 10 times
#and also prints "Hi" at the ninth iteration

i=0
while ((i != 10))
do
        echo "Best school"
	((i++))
        if (( i == 9))
        then
                echo "Hi"
        fi
done
